//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public System.DateTime MessageDate { get; set; }
        public int InformationCategoryID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string GuestName { get; set; }
        public string Email { get; set; }
        public string MessageSubject { get; set; }
        public string MessageContent { get; set; }
        public string AdminContent { get; set; }
        public string AdditionField1 { get; set; }
        public string AdditionField2 { get; set; }
        public Nullable<int> AdditionField3 { get; set; }
    
        public virtual tMember tMember { get; set; }
    }
}
