//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Lease = new HashSet<Lease>();
            this.Picture = new HashSet<Picture>();
            this.RoomFacilities = new HashSet<RoomFacilities>();
            this.RoomFavorite = new HashSet<RoomFavorite>();
        }
    
        public int ID { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> RoomStyleID { get; set; }
        public string RoomType { get; set; }
        public string BuildCaseID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rent { get; set; }
        public Nullable<int> SquareFootage { get; set; }
        public Nullable<int> RoomPictureID { get; set; }
        public Nullable<int> RoomFacilityID { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual BuildCase BuildCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lease> Lease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual RoomStyle RoomStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomFacilities> RoomFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomFavorite> RoomFavorite { get; set; }
    }
}
